name: noto-fonts

on:
  push:
  pull_request:

jobs:
  noto-fonts:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        raku-version:
          - 'latest'

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v7

      - uses: Raku/setup-raku@v1
        with:
          raku-version: ${{ matrix.raku-version }}

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
               libfontconfig1-dev \
               libfreetype6-dev    \
               libharfbuzz-dev

      - name: Install App::FontSample dependencies
        run: zef install --/test --test-depends --deps-only .

      - name: Install optional Noto provider
        run: zef install NotoFonts-OT --verbose

      - name: Test Noto integration
        run: |
          raku -Ilib xt/0-use-notofonts.t
          raku -Ilib xt/1-waterfall-noto.t
